<UL id=nav>
  <table>
  <th>
    
</th>
<th>

</th>
<th>

</th>
<tr>
<td>


<b><A href="">CATALOGOS</A></b> 
<a class="item2" href="../catalogos/proveedores.php">Proveedores</a>
<a class="item2" href="../catalogos/agregarproducto.php">Agregar producto</a>
<a class="item2" href="../catalogos/agregarproveedor.php">Agregar proveedor</a>
<a class="item2" href="../catalogos/eliminarproducto.php">Eliminar producto</a>
<a class="item2" href="../catalogos/eliminarproveedor.php">Eliminar proveedor</a>
<br>
<b><A   href="../movimientos/formulario.php">MOVIMIENTOS</A></b> 
<br>
<b><A href="">ADMINISTRACION</A>
<a class="item2" href="../administracion/entradas_y_salidas.php">Entradas y/o Salidas</a>
<a class="item2" href="../administracion/records_por_folio.php">Records por folio</a>
<a class="item2" href="../administracion/anexar_records_por_folio.php">Anexar records a folio</a>
<a class="item2" href="../administracion/inventario_por_proveedor.php">Inventario por proveedor</a>
<a class="item2" href="../administracion/bp.php">Buscar producto por su nombre</a>
<a class="item2" href="../administracion/concentrado.php">concentrado</a>



<br>
</DIV>
</head> 





