<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
   
    <style type="text/css">
	  body { font: 10px tahoma; background: #ffffff; margin: 0; padding: 50px;}    
    </style>
    <link rel="stylesheet" type="text/css" href="../example1.css" />
    <script type="text/javascript" src="../DropDownMenuX.js"></script>
</head>
    <table cellspacing="0" cellpadding="0" id="menu1" class="ddmx">
    <tr>
        <td>
            <a class="item1" href="javascript:void(0)">CATALOGOS</a>
            <div class="section">
                <a class="item2" href="../catalogos/proveedores.php">Proveedores</a>
                <a class="item2" href="../catalogos/agregarproducto.php">Agregar producto</a>
                <a class="item2" href="../catalogos/agregarproveedor.php">Agregar proveedor</a>
				<a class="item2" href="../catalogos/eliminarproducto.php">Eliminar producto</a>
				<a class="item2" href="../catalogos/eliminarproveedor.php">Eliminar proveedor</a>
            </div>
        </td>
        <td>
            <a class="item1" href="../movimientos/formulario.php">MOVIMIENTOS</a>
            <!--<div class="section">
                <a class="item2" href="../movimientos/eci.php">Entradas a bodega</a>
                <a class="item2" href="../movimientos/dpi.php">Salidas de bodega por devolucion</a>
                <a class="item2" href="../movimientos/vmi.php">Salidas por venta de mostrador</a>
				<a class="item2" href="../movimientos/sti.php">Traspasos</a>
				<a class="item2" href="../movimientos/edi.php">Entradas diversas</a>
				<a class="item2" href="../movimientos/sdi.php">Salidas diversas</a>
			  </div>-->
        </td>
        <td>
            <a class="item1" href="javascript:void(0)">ADMINISTRACION</a>
            <div class="section">
                <a class="item2" href="../administracion/entradas_y_salidas.php">Entradas y/o Salidas</a>
				<a class="item2" href="../administracion/records_por_folio.php">Records por folio</a>
				<a class="item2" href="../administracion/anexar_records_por_folio.php">Anexar records a folio</a>
				
				<a class="item2" href="../administracion/inventario_por_proveedor.php">Inventario por proveedor</a>
				<a class="item2" href="../administracion/bp.php">Buscar producto por su nombre</a>
                                <a class="item2" href="../administracion/concentrado.php">concentrado</a>
            </div>
        </td>
        <td>
            <a class="item1" href="javascript:void(0)">AYUDA</a>
            <div class="section">
                <a class="item2" href="../ayuda/instalacion.html">Como instalar la base de datos</a>
            </div>
        </td>
    </tr>
 </table>
 